<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-47P2MTB" failures="1" tests="1" name="Test" time="9.371" errors="0" timestamp="2023-02-28T21:12:30 IST">
  <testcase classname="test.SwagLabs1LoginTests" name="@AfterMethod publishResult" time="0.004">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&amp;quot; because &amp;quot;this.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "this.test" is null
at test.SwagLabs1LoginTests.publishResult(SwagLabs1LoginTests.java:136)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod publishResult -->
  <testcase classname="test.SwagLabs1LoginTests" name="@AfterTest createReport" time="-1.677598950591E9">
    <skipped/>
  </testcase> <!-- @AfterTest createReport -->
  <testcase classname="test.SwagLabs1LoginTests" name="doLogin_ValidIdAndInvalidPwd_FailedLoginAndErrorMSG" time="2.722">
    <failure type="java.lang.AssertionError" message="did not expect [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/inventory.html]">
      <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/inventory.html]
at test.SwagLabs1LoginTests.doLogin_ValidIdAndInvalidPwd_FailedLoginAndErrorMSG(SwagLabs1LoginTests.java:91)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- doLogin_ValidIdAndInvalidPwd_FailedLoginAndErrorMSG -->
</testsuite> <!-- Test -->
